version: '3.8'

services:
  netbox:
    image: lscr.io/linuxserver/netbox:latest
    container_name: netbox
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUPERUSER_EMAIL=admin@example.com  # Change this to your superuser email
      - SUPERUSER_PASSWORD=supersecurepassword  # Change this to your superuser password
      - ALLOWED_HOST=*
      - DB_NAME=netbox
      - DB_USER=netbox
      - DB_PASSWORD=netboxpassword  # Change this to your database password
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=  # Assuming no password is set for Redis
      - REDIS_DB_TASK=0
      - REDIS_DB_CACHE=1
      - BASE_PATH=  #optional
      - REMOTE_AUTH_ENABLED=  #optional
      - REMOTE_AUTH_BACKEND=  #optional
      - REMOTE_AUTH_HEADER=  #optional
      - REMOTE_AUTH_AUTO_CREATE_USER=  #optional
      - REMOTE_AUTH_DEFAULT_GROUPS=  #optional
      - REMOTE_AUTH_DEFAULT_PERMISSIONS=  #optional
    volumes:
      - netbox_config:/config
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=netbox
      - POSTGRES_USER=netbox
      - POSTGRES_PASSWORD=netboxpassword  # Change this to your database password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  netbox_config:
  postgres_data:
  redis_data:
